---
title: "Research"
output: distill::distill_article
date: '2022-03-19'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Journal papers


1. **Nonolocal parametric balance equations in the space of signed measures**. to be published in Sbornik: Mathematics (with M. Staritsyn)
2. [Feedback Maximum Principle for Ensemble Control of Local Continuity Equations: An Application to Supervised Machine Learning](https://ieeexplore.ieee.org/abstract/document/9454440). IEEE Control Syst. Lett., 6 (2021), pp. 1046-1051 (with M. Staritsyn, R. Chertovskih, F.L. Pereira)
3. [Modeling of crowds in regions with moving obstacles](https://www.aimsciences.org/article/doi/10.3934/dcds.2021066?viewType=html). Discrete Contin. Dyn. Syst., 41 (2021), no. 14, pp. 5009 - 5036 (with N. Maltugueva)
4. [Impulsive control of nonlocal transport equations](https://www.sciencedirect.com/science/article/pii/S002203962030108X). Journal of Differential Equations, 269 (2020), no. 4, pp. 3585-3623 (with M.V. Staritsyn)
5. [Program strategies for a dynamic game in the space of measures](https://link.springer.com/article/10.1007/s11590-018-1318-y). Optimization Letters. 13 (2019), no. 8. pp. 1913-1925.
6. [Bang-Bang Theorem for a Coupled ODE-PDE Control System](https://link.springer.com/article/10.1007/s10958-019-04298-7). Journal of Mathematical Sciences 23 (2019), no, 2. pp. 146-158.
7. [Estimates of the Domain of Dependence for Scalar Conservation Laws](https://www.sciencedirect.com/science/article/pii/S0022039618302067). Journal of Differential Equations, 265 (2018), no. 4, pp. 1654-1677.
8. [On the regularity of the boundary of the integral funnel of a differential inclusion](https://link.springer.com/article/10.1134/S0012266116080048). Differential Equations,  52 (2016), no. 8, pp. 987-999.
9. [Optimal control of continuity equations](https://link.springer.com/article/10.1007/s00030-016-0357-2). Nonlinear Differ. Equ. Appl. (2016) 23: 21.
10. [On the modeling of moving populations through set evolution equations](http://www.aimsciences.org/article/doi/10.3934/dcds.2015.35.73). Discrete Contin. Dyn. Syst., 35 (2015), no. 1, pp. 73-98 (with R.M. Colombo and T. Lorenz).
11. [The variational stability of an optimal control problem for Volterra-type equations](https://link.springer.com/article/10.1134/S0037446614040090). Siberian Mathematical Journal, 55 (2014), no. 4, pp. 667-686 (with A. Tolstonogov).
12. [On the control of moving sets: positive and negative confinement results](https://epubs.siam.org/doi/abs/10.1137/12087791X). SIAM J. Control Optim., 51 (2013), no. 1, pp. 380-401 (with R.M. Colombo).
13. [Confinement strategies in a model for the interaction between individuals and a continuum](https://epubs.siam.org/doi/abs/10.1137/110854321). SIAM J. Appl. Dyn. Syst., 11 (2012), no. 2, pp. 741-770 (with R.M. Colombo).
14. [Relaxation of the optimal control problem for Goursat-Darboux system](https://link.springer.com/article/10.1134/S0037446606010095). Siberian Mathematical Journal, 52 (2011), no. 1, pp. 78-90.
15. [On solutions of the Goursat-Darboux inclusion with mixed boundary and distributed control constraints](http://www.mathnet.ru/php/archive.phtml?wshow=paper&jrnid=sjim&paperid=491&option_lang=rus). Siberian Journal of Industrial Mathematics, 11 (2008), no. 1, pp. 96-110 (in Russian).
16. [On the properties of solutions to the Goursat-Darboux problem with boundary and distributed controls](https://link.springer.com/article/10.1007/s11202-007-0092-3). Siberian Mathematical Journal, 48 (2007), no. 5, pp. 897-912.
17. [On solutions of the Goursat-Darboux system with boundary controls and distributed controls](https://link.springer.com/article/10.1134/S0012266107080125). Differential Equations, 43 (2007), no. 8, pp. 1142-1152.


## Conference papers

18. [Feedback Maximum Principle for a Class of Linear Continuity Equations Inspired by Optimal Impulsive Control](https://link.springer.com/chapter/10.1007\%2F978-3-030-77876-7_24). Lecture Notes in Computer Science: 20th Intern. Conf. on Mathematical Optimization Theory and Operations Research, MOTOR 2021. 2021. vol. 12755. pp. 356-368 (with M. Staritsyn and E. Goncharova).
19. [Optimality Conditions and Numerical Algorithms for Hybrid Control Systems](https://link.springer.com/chapter/10.1007/978-3-030-22629-9_33). Lecture Notes in Computer Science: 19th Intern. Conf. on Mathematical Optimization Theory and Operations Research, MOTOR 2019. (2019), vol. 11548, pp. 474-488 (with N. Maltugueva  and O. Samsonyuk).
20. [Impulsive Relaxation of Continuity Equations and Modeling of Colliding Ensembles](https://link.springer.com/chapter/10.1007/978-3-030-10934-9_26). Communications in Computer and Information Science: 9th Intern. Conf. on Optimization and Applications, OPTIMA 2018. (2019) , vol. 974. pp. 367-381 (with M.V. Staritsyn).
21. [Minimum time function of a non-autonomous control system](https://www.sciencedirect.com/science/article/pii/S2405896318332117). IFAC-PapersOnLine, 51 (2018), no. 32, pp. 704-707 (with V.A. Voronov).
22. [On a Class of Impulsive Control Problems for Continuity Equations](https://www.sciencedirect.com/science/article/pii/S2405896318331264). IFAC-PapersOnLine, 51 (2018), no. 32, pp. 468-473 (with M.V. Staritsyn).
23. [Numerical Algorithm for Optimal Control of Continuity Equations](http://ceur-ws.org/Vol-1987/paper67.pdf). Proc. of 8th Intern. Conf. on Optimization and Applications, OPTIMA-2017, pp. 467-474.
24. [Conservation laws in the modeling of moving crowds](https://publik.tuwien.ac.at/files/PubDat_228935.pdf). AIMS Series on Applied Mathematics: Proc. of the 14th International Conference "Hyperbolic Problems: Theory, Numerics, Applications (2014), vol. 8, pp. 467-474 (with R.M. Colombo, M. Garavello, M. Lecureux-Mercier).

## Preprints

